import { TranslationKey } from './en';

export const hi: Partial<Record<TranslationKey, string>> = {
  Reviews: 'समीक्षाएं', 'Farmer Reviews': 'किसान समीक्षाएं', 'Real experiences from farmers using AgriLink to make better market decisions.': 'बेहतर बाजार निर्णय लेने वाले किसानों के अनुभव।', Rating: 'रेटिंग',
  English: 'English', as: 'के रूप में', Platform: 'प्लेटफॉर्म', Account: 'खाता', 'Smart India Hackathon Prototype': 'स्मार्ट इंडिया हैकाथॉन प्रोटोटाइप', 'About AgriLink': 'AgriLink के बारे में', 'New to AgriLink?': 'AgriLink पर नए हैं?', 'Already have an account?': 'पहले से खाता है?', 'Mobile Number / Email': 'मोबाइल नंबर / ईमेल', 'Contact Us': 'संपर्क करें', 'Send us your question or request.': 'अपना सवाल या अनुरोध भेजें।', 'Your request has been submitted successfully.': 'आपका अनुरोध सफलतापूर्वक भेज दिया गया है।', Name: 'नाम', 'Email / Phone': 'ईमेल / फोन', Subject: 'विषय', Message: 'संदेश', Submit: 'जमा करें', 'Contact Requests': 'संपर्क अनुरोध', 'Review and manage contact requests.': 'संपर्क अनुरोधों की समीक्षा और प्रबंधन करें।', 'No contact requests yet': 'अभी कोई संपर्क अनुरोध नहीं', 'Submitted Contact Us requests will appear here.': 'जमा किए गए संपर्क अनुरोध यहां दिखाई देंगे।', Date: 'तारीख', Status: 'स्थिति', 'Contact Request': 'संपर्क अनुरोध', 'Solution / Reply': 'समाधान / जवाब', 'Save Reply and Resolve': 'जवाब सहेजें और हल करें', Pending: 'लंबित', Approved: 'स्वीकृत', Rejected: 'अस्वीकृत', Resolved: 'हल किया गया',
  'हिन्दी': 'हिन्दी',
  'मराठी': 'मराठी',
  Home: 'होम', 'Market Prices': 'बाजार भाव', 'Compare Markets': 'बाजार तुलना', Marketplace: 'मार्केटप्लेस', 'Sell Produce': 'उपज बेचें', About: 'हमारे बारे में', Dashboard: 'डैशबोर्ड', Login: 'लॉगिन', Register: 'रजिस्टर', 'Log out': 'लॉग आउट',
  'Better markets. Better prices. Better income.': 'बेहतर बाजार। बेहतर भाव। बेहतर आय।', 'Check Market Prices': 'बाजार भाव देखें', 'Sell Your Produce': 'अपनी उपज बेचें', 'Today’s highlight': 'आज की खास जानकारी', 'Modal Price': 'मॉडल भाव', 'Est. Net Earnings*': 'अनुमानित शुद्ध कमाई*', 'Find the best market for your crop': 'अपनी फसल के लिए बेहतर बाजार खोजें', 'Select crop': 'फसल चुनें', 'Select state': 'राज्य चुनें', 'District / Location': 'जिला / स्थान', 'Find Best Market': 'बेहतर बाजार खोजें', 'Today’s Market Prices': 'आज के बाजार भाव', 'View all': 'सभी देखें', 'How AgriLink Works': 'AgriLink कैसे काम करता है', 'Key Benefits': 'मुख्य लाभ',
  'Discover Today’s Crop Prices': 'आज के फसल भाव देखें', 'Search and compare mandi prices across markets.': 'अलग-अलग बाजारों के मंडी भाव खोजें और तुलना करें।', 'All crops': 'सभी फसलें', 'All states': 'सभी राज्य', 'All districts': 'सभी जिले', 'All markets': 'सभी बाजार', Search: 'खोजें', 'Fetching latest prices...': 'नवीनतम भाव लाए जा रहे हैं...', 'No prices found': 'कोई भाव नहीं मिला', 'Try clearing a filter or choosing a different crop or district.': 'फिल्टर हटाएं या दूसरी फसल अथवा जिला चुनें।', Crop: 'फसल', Market: 'बाजार', District: 'जिला', 'Min Price': 'न्यूनतम भाव', 'Max Price': 'अधिकतम भाव', Change: 'बदलाव', Distance: 'दूरी', Updated: 'अपडेट', 'View Market': 'बाजार देखें',
  'Farmer Marketplace': 'किसान मार्केटप्लेस', 'Connect directly with farmers and verified buyers.': 'किसानों और सत्यापित खरीदारों से सीधे जुड़ें।', 'All categories': 'सभी श्रेणियां', 'All locations': 'सभी स्थान', 'Loading listings...': 'लिस्टिंग लोड हो रही हैं...', 'No listings match your filters': 'आपके फिल्टर से कोई लिस्टिंग नहीं मिली', 'Try widening your search or clearing a filter.': 'खोज बढ़ाएं या कोई फिल्टर हटाएं।', 'Contact Farmer': 'किसान से संपर्क करें', 'Send Enquiry': 'पूछताछ भेजें', 'Listing published': 'लिस्टिंग प्रकाशित हो गई', 'View Marketplace': 'मार्केटप्लेस देखें', 'Crop Name': 'फसल का नाम', 'Variety (optional)': 'किस्म (वैकल्पिक)', Quantity: 'मात्रा', Unit: 'इकाई', 'Expected Price': 'अपेक्षित भाव', 'Price Unit': 'भाव की इकाई', State: 'राज्य', Village: 'गांव', 'Village / Location': 'गांव / स्थान', 'Harvest Date': 'कटाई की तारीख', 'Quality Grade': 'गुणवत्ता ग्रेड', 'Product Description': 'उपज का विवरण', 'Image Upload': 'फोटो अपलोड', 'Contact Preference': 'संपर्क का माध्यम', 'Publish Listing': 'लिस्टिंग प्रकाशित करें', 'Publishing...': 'प्रकाशित हो रही है...',
  Compare: 'तुलना करें', 'Profit Calculator': 'लाभ कैलकुलेटर', 'Gross Revenue': 'कुल आय', 'Transportation Cost': 'परिवहन लागत', 'Estimated Net Revenue': 'अनुमानित शुद्ध आय', 'My Price Alerts': 'मेरे भाव अलर्ट', 'Get notified when your crop hits your target price.': 'फसल का भाव लक्ष्य तक पहुंचने पर सूचना पाएं।', 'Add Alert': 'अलर्ट जोड़ें', 'No price alerts yet': 'अभी कोई भाव अलर्ट नहीं', 'Target Price': 'लक्ष्य भाव', 'Current Price': 'वर्तमान भाव', Watching: 'निगरानी में', 'Target reached': 'लक्ष्य पूरा हुआ', 'Edit Alert': 'अलर्ट संपादित करें', 'Add Price Alert': 'भाव अलर्ट जोड़ें', 'Save Changes': 'बदलाव सहेजें',
  'Welcome back': 'वापसी पर स्वागत है', 'Log in to AgriLink to continue.': 'जारी रखने के लिए AgriLink में लॉगिन करें।', Farmer: 'किसान', Buyer: 'खरीदार', Password: 'पासवर्ड', 'Forgot Password?': 'पासवर्ड भूल गए?', 'Create Account': 'खाता बनाएं', 'Create your account': 'अपना खाता बनाएं', 'Join AgriLink as a farmer or a buyer.': 'AgriLink से किसान या खरीदार के रूप में जुड़ें।', 'I am a Farmer': 'मैं किसान हूं', 'I am a Buyer': 'मैं खरीदार हूं', Back: 'पीछे',
  'Active Listings': 'सक्रिय लिस्टिंग', 'Total Enquiries': 'कुल पूछताछ', 'Best Crop Price Today': 'आज का बेहतर फसल भाव', 'Saved Markets': 'सहेजे गए बाजार', 'Price Alerts': 'भाव अलर्ट', 'My Active Listings': 'मेरी सक्रिय लिस्टिंग', 'Recent Enquiries': 'हाल की पूछताछ', 'Market Demand': 'बाजार की मांग', 'Markets Near You': 'आपके पास के बाजार', Accept: 'स्वीकार करें', View: 'देखें', Current: 'वर्तमान', Average: 'औसत', Highest: 'अधिकतम', Lowest: 'न्यूनतम', '3 Months': '3 महीने', Days: 'दिन', Stable: 'स्थिर', 'High Demand': 'अधिक मांग', 'Medium Demand': 'मध्यम मांग', 'Low Demand': 'कम मांग', Open: 'खुला', 'Best current opportunity': 'वर्तमान में सबसे अच्छा अवसर', 'View Prices': 'भाव देखें', Grade: 'ग्रेड', Harvested: 'कटाई', 'View Details': 'विवरण देखें', Contact: 'संपर्क करें', Description: 'विवरण', 'Listing not found': 'लिस्टिंग नहीं मिली', 'Loading listing...': 'लिस्टिंग लोड हो रही है...', 'Enquiry Sent': 'पूछताछ भेज दी गई', 'Confirm & Send': 'पुष्टि करके भेजें', Close: 'बंद करें', 'Loading...': 'लोड हो रहा है...',
  Wheat: 'गेहूं', Rice: 'चावल', Soybean: 'सोयाबीन', Onion: 'प्याज', Tomato: 'टमाटर', Potato: 'आलू', Maize: 'मक्का', Mustard: 'सरसों', 'Chana (Gram)': 'चना', Turmeric: 'हल्दी', Mango: 'आम', Cotton: 'कपास', Grains: 'अनाज', Vegetables: 'सब्जियां', Fruits: 'फल', Pulses: 'दालें', Oilseeds: 'तिलहन', Spices: 'मसाले', Quintal: 'क्विंटल', Kg: 'किलो', Ton: 'टन',
};